server:
    port: 7777
spring:
    application:
        name: ymjhuahua-config
    cloud:
        config:
            server:
                git:
                    uri: https://github.com//test.git
                    search-paths: my-sample-config
                    username:
                    password:
eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/